version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - sail
        environment:
            - APP_NAME="Municipality"
            - APP_ENV=local
            - APP_KEY=base64:mXouEHDVQd6YlJ8qrZlNWLF2mDV34+ivDdAn4Y57pac=
            - APP_DEBUG=false
            - APP_TIMEZONE=UTC

            - APP_URL=https://municipal-system.laraplay.fun/
            - ASSET_URL=https://municipal-system.laraplay.fun/
            - VITE_APP_URL=https://municipal-system.laraplay.fun/

            - APP_LOCALE=ar
            - APP_FALLBACK_LOCALE=ar
            - APP_FAKER_LOCALE=en_US

            - APP_MAINTENANCE_DRIVER=file


            - BCRYPT_ROUNDS=12

            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug


            - DB_CONNECTION=sqlite

            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null

            - BROADCAST_CONNECTION=log
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=database

            - CACHE_STORE=database
            - CACHE_PREFIX=

            - MEMCACHED_HOST=127.0.0.1

            - REDIS_CLIENT=phpredis
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

            - MAIL_MAILER=log
            - MAIL_HOST=127.0.0.1
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"

            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false

            - VITE_APP_NAME="${APP_NAME}"




networks:
    sail:
        driver: bridge
