[phases.install]
cmds = ["mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx", "composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs", "npm i", "npm audit fix"]

[phases.build]
cmds = ["echo build started", "npm run build", "php artisan migrate:fresh --seed --force", "echo build ended", "chmod 777 /database/database.sqlite", "chmod -R 775 storage/framework/sessions", "php artisan config:clear", "php artisan cache:clear", "php artisan route:clear", "php artisan view:clear"]
